import {
  HomeOutline,
  HelpBuoyOutline,
  CartOutline,
  BagOutline,
  MenuOutline,
  LocateOutline,
  AnalyticsOutline,
  BookOutline,
  ChatboxEllipsesOutline,
  PersonOutline,
  Person,
  TicketOutline,
  FileTrayFullOutline,
  LinkOutline,
  ManSharp,
  StatsChart,
  SettingsOutline,
  BaseballOutline,
  CardOutline,
  CartSharp,
  BicycleOutline,
  OptionsOutline,
  CloudOutline,
  NotificationsOutline,
  ImageSharp,
  ManOutline,
} from "@vicons/ionicons5";
import type { Component } from "vue";

/** 图标映射 */
export const ICON_MAP: Record<string, Component> = {
  help: HelpBuoyOutline,
  "home-filled": HomeOutline,
  "shopping-bag": BagOutline,
  "shopping-cart-full": CartSharp,
  menu: MenuOutline,
  aim: LocateOutline,
  postcard: TicketOutline,
  user: PersonOutline,
  "user-filled": Person,
  "data-analysis": AnalyticsOutline,
  "message-box": FileTrayFullOutline,
  reading: BookOutline,
  comment: ChatboxEllipsesOutline,
  management: ManOutline,
  coordinate: ManSharp,
  connection: LinkOutline,
  histogram: StatsChart,
  setting: SettingsOutline,
  baseball: BaseballOutline,
  "credit-card": CardOutline,
  "shopping-cart": CartOutline,
  bicycle: BicycleOutline,
  "set-up": OptionsOutline,
  "mostly-cloudy": CloudOutline,
  notification: NotificationsOutline,
  "picture-filled": ImageSharp,
};
